### ISSUE TITLE
How to distinguish multiple button events

### ISSUE THREAD

**Issue by ForgetCSX** [espressif/esp-iot-solution#144] opened 2021-12-05 12:18 UTC
1, how to detect multiple button events, now the routine just gives a press detection, whether you can distinguish between different events through callback function parameters. 
2, multiple buttons can share a callback function

**Comment by leeebo** [comment] 2021-12-06 12:35
Hi@1404360768,  the callback function has a `void*` param, which is the button handle by default. You can use the handle to distinguish different buttons. https://github.com/espressif/esp-iot-solution/blob/master/components/button/test/button_test.c#L44

**Comment by 1404360768** [comment] 2021-12-06 12:52
Thank you, I actually ignored this example, haha

**Comment by franz-ms-muc** [comment] 2022-08-17 16:39
https://github.com/franz-ms-muc/esp-iot-solution/tree/feature/Fix_usr_data

**Comment by franz-ms-muc** [comment] 2022-08-17 16:39
Pull Request: #202

**Comment by chegewara** [comment] 2022-09-09 22:24
Im not sure if this is by design, but i believe this is a bug. 
In this line is missing `btn->event = (uint8_t)BUTTON_PRESS_REPEAT;` 
https://github.com/espressif/esp-iot-solution/blob/master/components/button/iot_button.c#L117
or `iot_button_get_repeat` will never catch `BUTTON_PRESS_REPEAT` when we have the same callback for many events.

Thanks

**Comment by leeebo** [comment] 2023-07-10 10:31
Fixed by https://github.com/espressif/esp-iot-solution/commit/0f767f9cec3bf4090fc70dab981fa2fcfb28401b

**Closed by leeebo** 2023-07-10 10:31 UTC
Labels: component: button
